
- name: assert all vars are set
  assert: 
    that:
      - item is defined
      - item | length > 0
    quiet: true
  loop:
  - installation_folder

- name: remove installation folder
  file:
    path: "{{ installation_folder }}"
    state: absent
  become: yes